title: GeFiCa
description: Germanium detector Field Calculator
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

github:
  zip_url: https://github.com/jintonic/gefica/zipball/master
  tar_url: https://github.com/jintonic/gefica/tarball/master
